# Generated by Django 5.2.5 on 2025-11-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_remove_token_tiempo_validez_minutos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participante",
            options={
                "permissions": [
                    ("aceptar_participante", "Aceptar Participante"),
                    ("ver_cv_participante", "Ver el CV de Participante"),
                    ("ver_dni_telefono_participante", "Ver el DNI de Participante"),
                ],
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
        ),
    ]
