# Generated by Django 5.1.13 on 2025-11-09 17:52

import django.core.validators
import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0009_alter_participante_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participante",
            options={
                "permissions": [
                    ("aceptar_participante", "Aceptar Participante"),
                    ("ver_cv_participante", "Ver el CV de Participante"),
                    (
                        "ver_dni_telefono_participante",
                        "Ver el DNI y el teléfono de Participante",
                    ),
                ],
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
        ),
        migrations.AlterModelOptions(
            name="persona",
            options={"ordering": ["-fecha_registro"]},
        ),
        migrations.AlterField(
            model_name="participante",
            name="ano_nacimiento",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1970, "El año debe ser mayor o igual a 1970."
                    ),
                    django.core.validators.MaxValueValidator(
                        2015, "El año debe ser menor o igual a 2015."
                    ),
                ],
                verbose_name="Año de nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="centro_estudio",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Centro de estudios"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="ciudad",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Ciudad de residencia"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="curso",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Curso actual"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="motivacion",
            field=models.TextField(null=True, verbose_name="Motivación"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nivel_estudio",
            field=models.CharField(
                choices=[
                    ("FORMACION_PROFESIONAL", "Formación Profesional"),
                    ("UNIVERSIDAD", "Universidad"),
                    ("MASTER", "Máster"),
                    ("OTRO", "Otro (Especificar en notas)"),
                ],
                max_length=128,
                null=True,
                verbose_name="Nivel actual de estudios",
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nombre_estudio",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Nombre de los estudios"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="quiere_creditos",
            field=models.BooleanField(default=False, verbose_name="Quiere créditos?"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="telefono",
            field=models.CharField(max_length=16, null=True, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="pase",
            name="tipo_pase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pases",
                to="gestion.tipopase",
                verbose_name="Tipo de pase",
            ),
        ),
        migrations.AlterField(
            model_name="patrocinador",
            name="acreditacion",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Acreditación",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="acreditacion",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Acreditación",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="compartir_cv",
            field=models.BooleanField(
                default=False, verbose_name="Autoriza a compartir el CV"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="cv",
            field=models.FileField(
                null=True,
                upload_to=gestion.models.ruta_cv,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    gestion.models.validador_pdf,
                ],
                verbose_name="CV",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dni",
            field=models.CharField(
                max_length=9, null=True, unique=True, verbose_name="DNI"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_aceptacion",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de aceptación"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_confirmacion_plaza",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Fecha de confirmación de la plaza",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de registro"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_verificacion_correo",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Fecha de verificación del correo",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[("HOMBRE", "Hombre"), ("MUJER", "Mujer"), ("OTRO", "Otro")],
                max_length=10,
                null=True,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="talla_camiseta",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=10,
                null=True,
                verbose_name="Talla de la camiseta",
            ),
        ),
        migrations.AlterField(
            model_name="tipopase",
            name="inicio_validez",
            field=models.DateTimeField(verbose_name="Inicio de la validez"),
        ),
        migrations.AlterField(
            model_name="token",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="fecha_expiracion",
            field=models.DateTimeField(verbose_name="Fecha de expiración"),
        ),
        migrations.AlterField(
            model_name="token",
            name="fecha_uso",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de uso"
            ),
        ),
    ]
