# Generated by Django 5.1.7 on 2025-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_participante_options_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_rechazo_plaza',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de rechazo de la plaza'),
        ),
    ]
