# Generated by Django 5.2.8 on 2025-11-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_persona_fecha_rechazo_plaza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participante",
            name="ano_nacimiento",
        ),
        migrations.AddField(
            model_name="participante",
            name="fecha_nacimiento",
            field=models.DateField(null=True, verbose_name="Fecha de nacimiento"),
        ),
    ]
