# Generated by Django 5.2.5 on 2025-08-18 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "dni",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PATROCINADOR", "Patrocinador"),
                            ("PARTICIPANTE", "Participante"),
                            ("MENTOR", "Mentor"),
                        ],
                        default="PARTICIPANTE",
                        max_length=50,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOMBRE", "Hombre"),
                            ("MUJER", "Mujer"),
                            ("OTRO", "Otro"),
                        ],
                        help_text="Género de la persona.",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(blank=True, default=None, null=True, unique=True),
                ),
                ("aceptado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RestriccionAlimentaria",
            fields=[
                ("id_restriccion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Restricción Alimentaria",
                "verbose_name_plural": "Restricciones Alimentarias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPase",
            fields=[
                ("id_tipo_pase", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("fecha_inicio_validez", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Tipo de Pase",
                "verbose_name_plural": "Tipos de Pase",
                "ordering": ["fecha_inicio_validez"],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "correo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mentor",
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                (
                    "tamano_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Pequeña"),
                            ("M", "Mediana"),
                            ("L", "Grande"),
                            ("XL", "Extra Grande"),
                            ("XXL", "Extra Extra Grande"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("compartir_cv", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentores",
            },
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "correo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="participante",
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "ano_nacimiento",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1970, "El año debe ser mayor o igual a 1970."
                            ),
                            django.core.validators.MaxValueValidator(
                                2015, "El año debe ser menor o igual a 2015."
                            ),
                        ],
                    ),
                ),
                (
                    "nivel_estudio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FORMACION_PROFESIONAL", "Formación Profesional"),
                            ("UNIVERSIDAD", "Universidad"),
                            ("MASTER", "Máster"),
                            ("OTRO", "Otro"),
                        ],
                        help_text="Nivel de estudios en curso.",
                        null=True,
                    ),
                ),
                (
                    "nombre_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "centro_estudios",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("curso", models.CharField(blank=True, max_length=128, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=128, null=True)),
                ("quiere_creditos", models.BooleanField(default=False)),
                (
                    "tamano_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Pequeña"),
                            ("M", "Mediana"),
                            ("L", "Grande"),
                            ("XL", "Extra Grande"),
                            ("XXL", "Extra Extra Grande"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("motivacion", models.TextField(blank=True, null=True)),
                ("compartir_cv", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
        ),
        migrations.CreateModel(
            name="Patrocinador",
            fields=[
                (
                    "correo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patrocinador",
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
            },
        ),
        migrations.AddField(
            model_name="persona",
            name="restricciones_alimentarias",
            field=models.ManyToManyField(
                blank=True,
                db_table="persona_restriccion_alimentaria",
                related_name="personas",
                to="hackudc.restriccionalimentaria",
            ),
        ),
        migrations.CreateModel(
            name="Presencia",
            fields=[
                ("id_presencia", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_entrada", models.DateTimeField()),
                ("fecha_salida", models.DateTimeField()),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempo_acceso",
                        to="hackudc.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presencia",
                "verbose_name_plural": "Presencias",
            },
        ),
        migrations.CreateModel(
            name="Pase",
            fields=[
                ("id_pase", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_pase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="hackudc.tipopase",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="hackudc.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase",
                "verbose_name_plural": "Pases",
                "ordering": ["fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(fields=["uuid"], name="hackudc_per_uuid_28b341_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="presencia",
            unique_together={("participante", "fecha_entrada", "fecha_salida")},
        ),
        migrations.AlterUniqueTogether(
            name="pase",
            unique_together={("participante", "tipo_pase", "fecha")},
        ),
    ]
