# Generated by Django 5.1.7 on 2025-10-05 16:56

import django.core.validators
import django.db.models.deletion
import hackudc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "acreditacion",
                    models.CharField(
                        blank=True, default=None, max_length=8, null=True, unique=True
                    ),
                ),
                (
                    "dni",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOMBRE", "Hombre"),
                            ("MUJER", "Mujer"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "talla_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        null=True,
                        upload_to=hackudc.models.ruta_cv,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            hackudc.models.validador_pdf,
                        ],
                    ),
                ),
                ("compartir_cv", models.BooleanField(default=False)),
                ("aceptado", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RestriccionAlimentaria",
            fields=[
                ("id_restriccion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Restricción Alimentaria",
                "verbose_name_plural": "Restricciones Alimentarias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPase",
            fields=[
                ("id_tipo_pase", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("inicio_validez", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Tipo de Pase",
                "verbose_name_plural": "Tipos de Pase",
                "ordering": ["inicio_validez"],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentores",
                "abstract": False,
            },
            bases=("hackudc.persona",),
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "ano_nacimiento",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1970, "El año debe ser mayor o igual a 1970."
                            ),
                            django.core.validators.MaxValueValidator(
                                2015, "El año debe ser menor o igual a 2015."
                            ),
                        ],
                    ),
                ),
                (
                    "nivel_estudio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FORMACION_PROFESIONAL", "Formación Profesional"),
                            ("UNIVERSIDAD", "Universidad"),
                            ("MASTER", "Máster"),
                            ("OTRO", "Otro (Especificar en notas)"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "nombre_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "centro_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("curso", models.CharField(blank=True, max_length=128, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=128, null=True)),
                ("quiere_creditos", models.BooleanField(default=False)),
                ("motivacion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "abstract": False,
            },
            bases=("hackudc.persona",),
        ),
        migrations.AddField(
            model_name="persona",
            name="restricciones_alimentarias",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)ss",
                to="hackudc.restriccionalimentaria",
            ),
        ),
        migrations.CreateModel(
            name="Patrocinador",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "acreditacion",
                    models.CharField(
                        blank=True, default=None, max_length=8, null=True, unique=True
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                (
                    "restricciones_alimentarias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)ss",
                        to="hackudc.restriccionalimentaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Presencia",
            fields=[
                ("id_presencia", models.AutoField(primary_key=True, serialize=False)),
                ("entrada", models.DateTimeField()),
                ("salida", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempo_acceso",
                        to="hackudc.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presencia",
                "verbose_name_plural": "Presencias",
                "unique_together": {("persona", "entrada", "salida")},
            },
        ),
        migrations.CreateModel(
            name="Pase",
            fields=[
                ("id_pase", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="hackudc.persona",
                    ),
                ),
                (
                    "tipo_pase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="hackudc.tipopase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase",
                "verbose_name_plural": "Pases",
                "ordering": ["fecha"],
                "unique_together": {("persona", "tipo_pase", "fecha")},
            },
        ),
    ]
