# Generated by Django 5.2.5 on 2025-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="aceptado",
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_aceptacion",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_confirmacion_plaza",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_verificacion_correo",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
