# Generated by Django 5.1.12 on 2025-09-18 00:01

import hackudc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0002_alter_tipopase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="cv",
            field=models.FileField(
                null=True, upload_to=hackudc.models.Participante.ruta_cv
            ),
        ),
    ]
