# Generated by Django 5.1.7 on 2025-10-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0003_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presencia",
            name="entrada",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
