# Generated by Django 5.1.12 on 2025-10-05 13:14

import django.core.validators
import hackudc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0005_change_participante_persona_pase_presencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="cv",
            field=models.FileField(
                null=True,
                upload_to=hackudc.models.ruta_cv,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    hackudc.models.validador_pdf,
                ],
            ),
        ),
    ]
