# Generated by Django 5.2.5 on 2025-10-27 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0006_sqlite_pragmas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="ano_nacimiento",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1970, "El año debe ser mayor o igual a 1970."
                    ),
                    django.core.validators.MaxValueValidator(
                        2015, "El año debe ser menor o igual a 2015."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="centro_estudio",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="ciudad",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="curso",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="motivacion",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nivel_estudio",
            field=models.CharField(
                choices=[
                    ("FORMACION_PROFESIONAL", "Formación Profesional"),
                    ("UNIVERSIDAD", "Universidad"),
                    ("MASTER", "Máster"),
                    ("OTRO", "Otro (Especificar en notas)"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nombre_estudio",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="telefono",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dni",
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[("HOMBRE", "Hombre"), ("MUJER", "Mujer"), ("OTRO", "Otro")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="talla_camiseta",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
